# Generated by Django 4.2.8 on 2024-01-22 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_ingredient_alter_recipe_options_recipe_author_and_more'),
    ]

    operations = [
    ]
