# Generated by Django 4.2.8 on 2024-01-22 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_alter_recipe_ingredients'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='recipe',
        #     name='ingredients',
        #     field=models.ManyToManyField(to='recipes.ingredient'),
        # ),
    ]

