# Generated by Django 4.2.8 on 2024-01-27 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeingredients', '0001_initial'),
        ('ingredients', '0001_initial'),
        ('recipes', '0010_alter_recipe_options_remove_recipe_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(blank=True, through='recipeingredients.RecipeIngredient', to='ingredients.ingredient'),
        ),
    ]
