# Generated by Django 4.2.6 on 2024-02-17 03:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_recipe_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
